[package]
name = 'substrate-validator-set'
version = '1.0.0'
authors = ['Gautam Dhameja <quasijatt@outlook.com>']
edition = '2021'
license = 'Apache-2.0'
repository = 'https://github.com/gautamdhameja/substrate-validator-set'

[dev-dependencies.serde]
features = ['derive']
version = '1.0.126'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/nagara-network/substrate.git'
branch = 'nagara-network-v1.0.0-alpha'

[dependencies.sp-io]
default-features = false
git = 'https://github.com/nagara-network/substrate.git'
branch = 'nagara-network-v1.0.0-alpha'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/nagara-network/substrate.git'
branch = 'nagara-network-v1.0.0-alpha'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/nagara-network/substrate.git'
branch = 'nagara-network-v1.0.0-alpha'

[dependencies.sp-staking]
default-features = false
git = 'https://github.com/nagara-network/substrate.git'
branch = 'nagara-network-v1.0.0-alpha'

[dependencies.log]
default-features = false
version = '0.4.17'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '3.0.0'

[dependencies.frame-benchmarking]
default-features = false
git = 'https://github.com/nagara-network/substrate.git'
optional = true
branch = 'nagara-network-v1.0.0-alpha'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/nagara-network/substrate.git'
branch = 'nagara-network-v1.0.0-alpha'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/nagara-network/substrate.git'
branch = 'nagara-network-v1.0.0-alpha'

[dependencies.pallet-session]
default-features = false
features = ['historical']
git = 'https://github.com/nagara-network/substrate.git'
branch = 'nagara-network-v1.0.0-alpha'

[dependencies.scale-info]
default-features = false
features = ['derive']
version = '2.1.1'

[features]
default = ['std']
runtime-benchmarks = ['frame-benchmarking/runtime-benchmarks']
std = [
    'codec/std',
    'frame-benchmarking/std',
    'frame-support/std',
    'frame-system/std',
    'scale-info/std',
    'sp-core/std',
    'sp-io/std',
    'sp-std/std',
    'sp-runtime/std',
    'pallet-session/std',
]
try-runtime = ['frame-support/try-runtime']
